/**
 * Russian → English translations for the developer language switch (see
 * i18n.ts). Keyed by the exact Russian source string used in the components.
 * A missing key falls back to Russian, so partial coverage is always safe.
 * `{name}`-style placeholders are filled in by t() after lookup.
 *
 * This exists ONLY so the developer can test in English. She always sees
 * Russian (P5).
 */
export const EN: Record<string, string> = {
  // ---- shared: ui / AppShell / alarm ----
  'Отмена': 'Cancel',
  'Подождите…': 'Please wait…',
  'Закрыть': 'Close',
  'Готово': 'Done',
  'Назад': 'Back',
  'На главную': 'Home',
  'Сохранить': 'Save',
  'Это устройство ещё не подключено': 'This device is not connected yet',
  'Чтобы всё заработало, нужно один раз открыть на этом устройстве специальную ссылку. Позвоните Даниилу — он поможет.':
    'To get everything working, open a special link once on this device. Call Daniel — he will help.',
  'Нет связи': 'No connection',
  'Проверьте интернет и попробуйте ещё раз.': 'Check your internet and try again.',
  'Попробовать ещё раз': 'Try again',
  'Напоминание': 'Reminder',
  'Показать через 5 минут': 'Remind me in 5 minutes',
  'и ещё {n} напоминание…': 'and {n} more reminder…',

  // ---- shared: Picker / files ----
  'Все файлы': 'All files',
  'Открыть': 'Open',
  'Действия': 'Actions',
  'Выберите папку': 'Choose a folder',
  'Выберите папку из списка.': 'Choose a folder from the list.',
  'Папок пока нет.': 'No folders yet.',
  'У вас пока нет папок.': "You don't have any folders yet.",
  'Создайте папку, чтобы сохранять туда файлы.': 'Create a folder to save files into.',
  'Слева выберите папку, чтобы увидеть файлы.': 'Choose a folder on the left to see its files.',
  'Файл должен быть в какой-нибудь папке.': 'The file must be in a folder.',
  'Не получилось загрузить папки.': 'Could not load folders.',
  'Папка:': 'Folder:',
  'Загрузка…': 'Loading…',
  'Здесь нет видео.': 'No videos here.',
  'Новая папка': 'New folder',
  'Название папки': 'Folder name',
  'Создать': 'Create',

  // ---- video ----
  'Видео': 'Video',
  'Загружаем видео…': 'Uploading video…',
  'Отменить': 'Cancel',
  'Какое видео будем менять?': 'Which video shall we edit?',
  'Выбрать видео с устройства': 'Choose a video from this device',
  'Выбрать из Файлов': 'Choose from Files',
  'Выберите видео': 'Choose a video',
  'Не получилось загрузить видео.': 'Could not upload the video.',
  'Не получилось открыть видео.': 'Could not open the video.',
  'Начало отмечено. Теперь доиграйте до конца нужной части и нажмите «Конец».':
    'Start marked. Now play to the end of the part you want and press “End”.',
  'Сначала нажмите «Начало».': 'Press “Start” first.',
  'Часть получилась слишком короткой. Передвиньте видео вперёд и нажмите «Конец».':
    'That part is too short. Move the video forward and press “End”.',
  'Пауза': 'Pause',
  'Смотреть': 'Play',
  'из {d}': 'of {d}',
  'скорость {s}×': 'speed {s}×',
  'Обрезать видео': 'Trim video',
  'Изменить скорость': 'Change speed',
  'Оставлено частей:': 'Parts kept:',
  'вместе': 'together',
  'Видео целиком:': 'Whole video:',
  'Скорость:': 'Speed:',
  '(медленнее)': '(slower)',
  'Итоговая длина:': 'Final length:',
  'Посмотреть, что получится': 'Preview the result',
  'Остановить просмотр': 'Stop preview',
  'Выберите, что сделать с видео. Можно и обрезать, и замедлить.':
    'Choose what to do with the video. You can both trim and slow it down.',
  'Продолжить': 'Continue',
  'Найдите нужную часть. Нажмите «Начало» там, где она начинается.':
    'Find the part you want. Press “Start” where it begins.',
  'Начало: {t}. Теперь нажмите «Конец» там, где часть заканчивается.':
    'Start: {t}. Now press “End” where the part finishes.',
  'Начало': 'Start',
  'Конец': 'End',
  'Отменить отметку': 'Cancel mark',
  'Часть {i}:': 'Part {i}:',
  'Убрать часть {i}': 'Remove part {i}',
  '−1 сек': '−1 sec',
  '+1 сек': '+1 sec',
  'Начало:': 'Start:',
  'Конец:': 'End:',
  'Выберите скорость. Звук останется обычным, не «писклявым».':
    'Choose a speed. The sound stays normal, not “squeaky”.',
  'Обычная скорость': 'Normal speed',
  'Нажмите «Смотреть», чтобы сразу услышать разницу.': 'Press “Play” to hear the difference right away.',
  'Выйти из монтажа?': 'Leave editing?',
  'Отмеченные части и скорость не сохранятся.': 'The marked parts and speed will not be saved.',
  'Выйти': 'Leave',
  'Проверьте и подтвердите': 'Check and confirm',
  'Оставляем частей: {n}': 'Keeping {n} parts',
  'Видео целиком, без обрезки.': 'The whole video, no trimming.',
  'обычная (1.0×)': 'normal (1.0×)',
  '{s}× — медленнее': '{s}× — slower',
  'Создать видео': 'Create video',
  'Начинаем…': 'Starting…',
  'Не получилось начать. Попробуйте ещё раз.': 'Could not start. Try again.',
  'Не получилось создать видео': 'Could not create the video',
  'Попробуйте ещё раз. Если не выходит — позвоните Даниилу.':
    'Try again. If it still fails, call Daniel.',
  'Готовим видео…': 'Preparing the video…',
  'Это может занять пару минут. Можно просто подождать здесь.':
    'This can take a couple of minutes. You can just wait here.',
  'Видео готово!': 'Video is ready!',
  'Длина: {d}': 'Length: {d}',
  'Сохранено в папке «{name}»': 'Saved in folder “{name}”',
  'Сохранить в Файлы': 'Save to Files',
  'Скачать': 'Download',
  'Сделать ещё одно видео': 'Make another video',
  'Куда сохранить видео?': 'Where to save the video?',
  'Сохранить в «{name}»': 'Save to “{name}”',
  'Не получилось сохранить.': 'Could not save.',

  // ---- files ----
  'Не получилось загрузить файлы.': 'Could not load files.',
  'Файл загружен': 'File uploaded',
  'Загружено файлов: {n}': 'Files uploaded: {n}',
  'Не получилось загрузить.': 'Could not upload.',
  'Не получилось создать папку.': 'Could not create the folder.',
  'Не получилось переименовать.': 'Could not rename.',
  'Папка перемещена в «{name}»': 'Folder moved to “{name}”',
  'Не получилось переместить папку.': 'Could not move the folder.',
  'Папка удалена': 'Folder deleted',
  'Не получилось удалить папку.': 'Could not delete the folder.',
  'Найти файл по названию…': 'Find a file by name…',
  'Очистить': 'Clear',
  'Ничего не нашлось. Попробуйте написать по-другому.': 'Nothing found. Try spelling it differently.',
  'Здесь пока пусто.': 'Empty here so far.',
  'Нажмите «Загрузить файлы», чтобы добавить сюда фото, видео или музыку.':
    'Press “Upload files” to add photos, videos or music here.',
  'Загружаем файл…': 'Uploading file…',
  'Загружаем файлы ({n})…': 'Uploading files ({n})…',
  'Поиск': 'Search',
  'Действия с папкой': 'Folder actions',
  'Загрузить файлы': 'Upload files',
  'Файлы': 'Files',
  'Файл удалён': 'File deleted',
  'Папка появится в «{name}».': 'The folder will appear in “{name}”.',
  'Создать папку': 'Create folder',
  'Папка «{name}»': 'Folder “{name}”',
  'Переименовать папку': 'Rename folder',
  'Переместить папку': 'Move folder',
  'Удалить папку': 'Delete folder',
  'Куда переместить папку?': 'Where to move the folder?',
  'Переместить в «{name}»': 'Move to “{name}”',
  'Переместить папку «{cur}» в «{name}»?': 'Move folder “{cur}” to “{name}”?',
  'Удалить папку «{name}»?': 'Delete folder “{name}”?',
  'В ней файлов: {n}. Они тоже будут удалены.': 'It has {n} files. They will be deleted too.',
  'Папка пустая.': 'The folder is empty.',

  // ---- files: Viewer ----
  'Файл теперь в папке «{name}»': 'The file is now in folder “{name}”',
  'Поделиться': 'Share',
  'Переместить': 'Move',
  'Переименовать': 'Rename',
  'Удалить': 'Delete',
  'Этот файл нельзя показать здесь.': 'This file cannot be shown here.',
  'Скачать файл': 'Download file',
  'Не получилось переместить.': 'Could not move.',
  'Не получилось удалить.': 'Could not delete.',
  'Куда переместить файл?': 'Where to move the file?',
  'Переместить файл в «{name}»?': 'Move the file to “{name}”?',
  'Файл перемещён': 'File moved',
  'Удалить файл?': 'Delete file?',
  '«{name}» будет удалён.': '“{name}” will be deleted.',
  'Переименовать файл': 'Rename file',
  'Постоянная ссылка на этот файл. Отправьте её в WhatsApp — человек увидит только этот один файл.':
    'A permanent link to this file. Send it in WhatsApp — the person will see only this one file.',
  'Скопировать ссылку': 'Copy link',
  'Скопировано': 'Copied',
  'Ссылка скопирована': 'Link copied',
  'Не получилось создать ссылку.': 'Could not create the link.',
  'Не получилось скопировать. Выделите ссылку пальцем.': 'Could not copy. Select the link by hand.',
  'Ссылка удалена': 'Link deleted',
  'Не получилось удалить ссылку.': 'Could not delete the link.',
  'Создать постоянную ссылку': 'Create permanent link',
  'Создаём…': 'Creating…',
  'Удалить ссылку': 'Delete link',
  'Удалить ссылку?': 'Delete link?',
  'Ссылка перестанет открываться у всех, кому вы её отправляли. Сам файл останется.':
    'The link will stop working for everyone you sent it to. The file itself stays.',

  // ---- reminders ----
  'Напоминания': 'Reminders',
  'сегодня —': 'today —',
  'Чтобы напоминания звонили на этом устройстве, разрешите уведомления.':
    'To let reminders ring on this device, allow notifications.',
  'Разрешить': 'Allow',
  'Сегодня': 'Today',
  'Сегодня напоминаний нет.': 'No reminders today.',
  'Завтра': 'Tomorrow',
  'Завтра напоминаний нет.': 'No reminders tomorrow.',
  'В этот день напоминаний нет.': 'No reminders on this day.',
  'Добавить напоминание': 'Add reminder',
  '— звонит!': '— ringing!',
  '— отложено до {time}': '— snoozed until {time}',
  'Удалить напоминание': 'Delete reminder',
  'Напоминание удалено': 'Reminder deleted',
  'Удалить напоминание?': 'Delete reminder?',
  '«{text}» больше не прозвонит.': '“{text}” will no longer ring.',
  'Новое напоминание': 'New reminder',
  'О чём напомнить?': 'What to remind about?',
  'Например: занятие по танцам': 'For example: dance class',
  'Какого числа?': 'On which day?',
  'Во сколько?': 'At what time?',
  'это время уже прошло': 'that time has already passed',
  'Напишите, о чём напомнить.': 'Write what to remind about.',
  'Это время уже прошло. Выберите время в будущем.': 'That time has already passed. Choose a time in the future.',
  'Напоминание создано': 'Reminder created',
  'Не получилось создать напоминание.': 'Could not create the reminder.',
  'Далее': 'Next',

  // ---- reminders: Calendar ----
  'Прошлый месяц': 'Previous month',
  'Следующий месяц': 'Next month',
  'Час больше': 'Hour up',
  'Час меньше': 'Hour down',
  'Минуты больше': 'Minutes up',
  'Минуты меньше': 'Minutes down',
};
